global:
  marketplace-ami: false
<<<<<<< HEAD
  owner: quickstart-eng@amazon.com
  qsname: quickstart-data-lake-cloudwick
  regions:
    - ap-northeast-1
    - ap-northeast-2
    - ap-south-1
    - ap-southeast-1
    - ap-southeast-2
    - ca-central-1
    - eu-central-1
    - eu-west-1
    - sa-east-1
    - us-east-1
    - us-east-2
    - us-west-1
    - us-west-2
  reporting: true
 
tests:
  quickstart-data-lake-cloudwickt1:
    parameter_input: quickstart-data-lake-cloudwick-example-params1.json
    template_file: quickstart-data-lake-cloudwick-example1.template
  quickstart-data-lake-cloudwickt2:
    parameter_input: quickstart-data-lake-cloudwick-example-params2.json
    template_file: quickstart-data-lake-cloudwick-example2.template
=======
  owner: quickstart@amazon.com
  #subjected to change
  qsname: quickstart-aws-datalake
  regions:
    - us-east-1
    - us-west-2
  reporting: true
tests:
  defaults:
    parameter_input: aws-datalake-defaults.json
    template_file: aws-datalake-qs.template
>>>>>>> 0575f0ed06c66e42f3835453c588024bf11c5eb5
